apiVersion: v1
kind: Namespace
metadata:
  name: iwiick-proj-1-staging
  labels:
    environmentId: env_11c7ddba-3fc5-42b4-92b2-2424c944eede
    projectId: project_f25ad2e4-cf21-410c-b7fb-a8adad864a23
    projectName: iwiick-proj-1
    environmentName: staging
    organizationId: org_d2ea4601-f582-4e43-921d-6a60eea704b3
