apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: ca378bc0bff1d86a0882ffdd2ff1c749b33d03bc
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts: []
      healthChecks: []
      name: iwiick-app-5-main
      imagePullPolicy: Always
      imageRegistry: ghcr.io/iwiick-insighture/pipeline
      imagePullSecretName: imagepull-github
      credentialId: credential_c38a1871-96b5-430f-822a-143f05ae0b83
      commitDetails:
        commitHash: ca378bc0bff1d86a0882ffdd2ff1c749b33d03bc
        commitAvatar: https://github.com/skyu-v2-dev[bot].png
        commitTime: '2024-01-09T03:36:35Z'
        commitMessage: >-
          "container-dev_env_2046883c-f8a3-4774-ae10-510d8ab9865a_app_5166c742-d409-4c22-9fe9-5b1fd4edba69
          workflow file created'"
        commitUser: skyu-v2-dev[bot]
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: iwiick-app-5
    version: v1.0.0
    applicationId: app_5166c742-d409-4c22-9fe9-5b1fd4edba69
    projectId: project_88e61e3d-8f14-4fe8-b600-517e8138c28d
    organizationId: org_9f875a32-727f-4fb0-aeb6-ad3b32168642
    environmentId: env_2046883c-f8a3-4774-ae10-510d8ab9865a
    environmentName: dev
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: iwiick-app-5
  serviceType: ClusterIP
  version: v1.0.0
  namespace: iwiick-proj-1-dev
