apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts: []
      healthChecks: []
      name: commit-msg-main
      imagePullPolicy: Always
      imageRegistry: docker.io/thameeragg/commit-msg
      imagePullSecretName: imagepull-docker
      credentialId: credential_2774fb83-54ac-40fb-ade5-dbf25ae4c5da
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: commit-msg
    version: v1.0.0
    applicationId: app_fd93edba-7f37-47ee-936c-184dc8ff8839
    projectId: project_f25ad2e4-cf21-410c-b7fb-a8adad864a23
    organizationId: org_d2ea4601-f582-4e43-921d-6a60eea704b3
    environmentId: env_3f34e2e8-6902-4eee-a0bb-281989189458
    environmentName: dev
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: commit-msg
  serviceType: ClusterIP
  version: v1.0.0
  namespace: iwiick-proj-1-dev
