apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts: []
      healthChecks: []
      name: test-app-main
      imagePullPolicy: Always
      imageRegistry: 272133924862.dkr.ecr.us-east-1.amazonaws.com/test-app
      credentialId: credential_94c8f187-0a1a-4f1d-93f9-e8bb10f14377
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: test-app
    version: v1.0.0
    applicationId: app_28745b6c-5e41-4edb-9273-55c695432859
    projectId: project_33d6eb31-f21a-4bbe-b322-75295d837ed8
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    environmentId: env_17cd2821-4820-4f49-bfd4-036afb45a8d2
    environmentName: staging
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: test-app
  serviceType: ClusterIP
  version: v1.0.0
  namespace: iwiick-staging
