apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-and-limited-ingress
  namespace: iwiick-proj-1-prod
  labels:
    organizationId: org_c3ee32e5-1a4f-4580-bb9f-9c113831aac2
    projectId: project_286d6538-6b3b-4615-bd43-c7c3b4d768ea
    environmentId: env_d6320c2c-d8ce-4d17-b878-4590b7201cc0
spec:
  podSelector: {}
  egress:
    - {}
  policyTypes:
    - Egress
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              environmentId: env_d6320c2c-d8ce-4d17-b878-4590b7201cc0
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: skyu-system
    - from:
        - namespaceSelector:
            matchLabels:
              role: ingress
    - from:
        - namespaceSelector:
            matchLabels:
              role: observability
