apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: test-app-v1-0-0
  labels:
    app: test-app-v1-0-0
    applicationId: app_28745b6c-5e41-4edb-9273-55c695432859
    version: v1.0.0
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_33d6eb31-f21a-4bbe-b322-75295d837ed8
    environmentId: env_ebe32f30-bb97-49c1-a273-69ecea6c203b
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-app-v1-0-0
