apiVersion: v1
kind: Namespace
metadata:
  name: iwiick-proj-1-dev
  labels:
    environmentId: env_3f34e2e8-6902-4eee-a0bb-281989189458
    projectId: project_f25ad2e4-cf21-410c-b7fb-a8adad864a23
    projectName: iwiick-proj-1
    environmentName: dev
    organizationId: org_d2ea4601-f582-4e43-921d-6a60eea704b3
