apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: bit-please-v1-0-0
    applicationId: app_0b8d035c-352b-47ae-853d-d0e4a781b968
    version: v1.0.0
    organizationId: org_d2ea4601-f582-4e43-921d-6a60eea704b3
    projectId: project_f25ad2e4-cf21-410c-b7fb-a8adad864a23
  name: bit-please-v1-0-0
spec:
  selector:
    app: bit-please-v1-0-0
