apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: 29babc3ae90d01f82211b34063a7834591e9caea
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts: []
      healthChecks: []
      name: general-new-main
      imagePullPolicy: Always
      imageRegistry: docker.io/thameeragg/general-new
      imagePullSecretName: imagepull-docker
      credentialId: credential_2774fb83-54ac-40fb-ade5-dbf25ae4c5da
      commitDetails:
        commitHash: 29babc3ae90d01f82211b34063a7834591e9caea
        commitAvatar: https://github.com/.png
        commitTime: ''
        commitMessage: ''
        commitUser: ''
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: general-new
    version: v1.0.0
    applicationId: app_eba6d026-bfaa-4ab6-91fd-a1183397a53f
    projectId: project_f25ad2e4-cf21-410c-b7fb-a8adad864a23
    organizationId: org_d2ea4601-f582-4e43-921d-6a60eea704b3
    environmentId: env_3f34e2e8-6902-4eee-a0bb-281989189458
    environmentName: dev
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: general-new
  serviceType: ClusterIP
  version: v1.0.0
  namespace: iwiick-proj-1-dev
