apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: iwiick-app-1-v1-0-0
  labels:
    app: iwiick-app-1-v1-0-0
    applicationId: app_d08e17b2-513a-4548-a883-1813652e0192
    version: v1.0.0
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_33d6eb31-f21a-4bbe-b322-75295d837ed8
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: iwiick-app-1-v1-0-0
