apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: iwiick-app-1-v1-0-0
  labels:
    app: iwiick-app-1-v1-0-0
    applicationId: app_62d0974a-7ea9-4419-bd82-9e4eb8a20642
    version: v1.0.0
    organizationId: org_66955b30-1a63-4c92-bd87-67a900920d99
    projectId: project_4400a997-b5f4-4bff-b1a7-8781f97ed034
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: iwiick-app-1-v1-0-0
