apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: b3b87a1e625b628994303206feb61afd39e26caa
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts: []
      healthChecks: []
      name: msg-main
      imagePullPolicy: Always
      imageRegistry: docker.io/thameeragg/msg
      imagePullSecretName: imagepull-docker
      credentialId: credential_2774fb83-54ac-40fb-ade5-dbf25ae4c5da
      commitDetails:
        commitHash: b3b87a1e625b628994303206feb61afd39e26caa
        commitTime: ''
        commitUser: ''
        commitAvatar: https://github.com/.png
        commitMessage: msg_pr-default-staging_app_d550f9d.yaml Created
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: msg
    version: v1.0.0
    applicationId: app_d550f9d0-76cd-4c94-be2c-da7afbdb6f33
    projectId: project_f25ad2e4-cf21-410c-b7fb-a8adad864a23
    organizationId: org_d2ea4601-f582-4e43-921d-6a60eea704b3
    environmentId: env_3f34e2e8-6902-4eee-a0bb-281989189458
    environmentName: dev
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: msg
  serviceType: ClusterIP
  version: v1.0.0
  namespace: iwiick-proj-1-dev
