apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: iwiick-app-3-v1-0-0
  labels:
    app: iwiick-app-3-v1-0-0
    applicationId: app_fd49ab28-f155-4dd4-a3dd-725d2bdf3803
    version: v1.0.0
    organizationId: org_9f875a32-727f-4fb0-aeb6-ad3b32168642
    projectId: project_88e61e3d-8f14-4fe8-b600-517e8138c28d
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: iwiick-app-3-v1-0-0
