apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: coffee-order-v1-0-0
  labels:
    app: coffee-order-v1-0-0
    applicationId: app_9a3ba3fb-ffb5-4f75-985c-243de3a598cb
    version: v1.0.0
    organizationId: org_5bdc6e05-06b5-4d67-91b9-f020de5fdd93
    projectId: project_a76ac38c-01c7-409e-b6f4-432611deb5fb
    environmentId: env_f3bc5278-0a45-4140-8082-729c836e5e6e
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: coffee-order-v1-0-0
