apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee-user-v1-0-0
  labels:
    app: coffee-user-v1-0-0
    applicationId: app_44260cd3-7525-47cf-9796-30e714b11d56
    version: v1.0.0
    organizationId: org_5bdc6e05-06b5-4d67-91b9-f020de5fdd93
    projectId: project_a76ac38c-01c7-409e-b6f4-432611deb5fb
    environmentId: env_17f5305d-6f79-43bf-9ab5-e29d700d8210
  annotations:
    reloader.stakater.com/auto: 'true'
spec:
  selector:
    matchLabels:
      app: coffee-user-v1-0-0
  template:
    metadata:
      labels:
        app: coffee-user-v1-0-0
        applicationId: app_44260cd3-7525-47cf-9796-30e714b11d56
        version: v1.0.0
        organizationId: org_5bdc6e05-06b5-4d67-91b9-f020de5fdd93
        projectId: project_a76ac38c-01c7-409e-b6f4-432611deb5fb
        environmentId: env_17f5305d-6f79-43bf-9ab5-e29d700d8210
