apiVersion: apps/v1
kind: Deployment
metadata:
  name: musatest-v1-0-0
  labels:
    app: musatest-v1-0-0
    applicationId: app_895b9cc0-9626-4348-a016-02ddf3b2fcb6
    version: v1.0.0
    organizationId: org_d2ea4601-f582-4e43-921d-6a60eea704b3
    projectId: project_f25ad2e4-cf21-410c-b7fb-a8adad864a23
    environmentId: env_3f34e2e8-6902-4eee-a0bb-281989189458
  annotations:
    reloader.stakater.com/auto: 'true'
spec:
  selector:
    matchLabels:
      app: musatest-v1-0-0
  template:
    metadata:
      labels:
        app: musatest-v1-0-0
        applicationId: app_895b9cc0-9626-4348-a016-02ddf3b2fcb6
        version: v1.0.0
        organizationId: org_d2ea4601-f582-4e43-921d-6a60eea704b3
        projectId: project_f25ad2e4-cf21-410c-b7fb-a8adad864a23
        environmentId: env_3f34e2e8-6902-4eee-a0bb-281989189458
